@startuml
package Dorama {

      package Services {
                package Interfaces {
       
}       

       
       
        }

        package Repository{
        
        package Implementations{
        
        
        }
        package Interfaces{
     
        
        }
}

        package models {
                package Dtos {
       
}
                package Entities {
        
            }
        

       
       
        }

        package Data {
        class AppDbContext 
        }




        package Controllers {
       
        }
        
               
        
}
@enduml
