@startuml
package Dorama {

        package Controllers {
       
        }
        
        
        package Data {
        class AppDbContext 
        }
        package models {
                package Dtos {
       
}
                package Entities {
        
            }
        

       
       
        }

        package Repository{
        
        package Implementations{
        
        
        }
        package Interfaces{
     
        
        }

        package Service{
        
        package Interfaces{
     
        }
        
}
@enduml
