@AvaliacaoApi_HostAddress = https://localhost:7004


###
POST {{AvaliacaoApi_HostAddress}}/usuarios
Content-Type: application/json

{
  "Nome": "larissa rangel",
  "Email": "larissa@gmail.com",
  "Senha": "12345"
}
###

GET https://localhost:7004/usuarios
###

